name: ci

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [12.x]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node}}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
        env:
          CI: true

  e2e:
    runs-on: ubuntu-16.04
    container: cypress/included:4.9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node}}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Start API
        env:
          API_PORT: 3100
          API_URL: http://localhost:3100
        run: |
          yarn api &
          yarn run dev &
          # wait for nuxt to build
          sleep 30
          npx wait-on 'http://localhost:3000'
          curl -XGET localhost:3000
      - name: Run E2E
        run: yarn e2e
