name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node}}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test
        env:
          CI: true

  e2e:
    runs-on: ubuntu-16.04
    container: cypress/included:4.9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node}}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Start API
        env:
          API_PORT: 3100
          API_URL: http://localhost:3100
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          DISABLE_HTTPS: true
        run: |
          yarn api &
          yarn run demo:build
          yarn run demo:start &
          npx wait-on 'http://localhost:3000'
          curl -XGET localhost:3000
      - name: Run E2E
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        run: yarn e2e

  deploy-next:
    if: github.ref == 'refs/heads/dev'
    needs: [test,e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Update package name and version number
        run: node ./scripts/bump-next
      - name: Build
        run: |
          yarn clean
          yarn build
      - name: Publish Next
        run: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
            npm publish
        env:
            GIT_REF: ${{ github.ref }}
            NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
