on:
  push:
    branches:
      - master

jobs:
  deploy:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node}}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Publish Next
        run: |
            if [ "$GIT_REF" = "refs/heads/dev" ] ; then
              node ./scripts/bump-next
              yarn clean
              yarn build
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
              npm publish
            fi
        env:
            GIT_REF: ${{ github.ref }}
            NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
